### ISSUE TITLE
PSAD 2.4.0: uninitialized value in concatenation (.) or string at /usr/sbin/psad line 6701

### ISSUE THREAD

**Issue by itoffshore** [mrash/psad#19]
This is under [Alpine Linux](http://alpinelinux.org) (without systemd / firewalld / journald)

The daemon starts ok but running `psad -L` shows:
```
[+] Listing chains from IPT_AUTO_CHAIN keywords...

Use of uninitialized value in concatenation (.) or string at /usr/sbin/psad line 6701.
[*]  -t filter -n -L PSAD_BLOCK_INPUT -v does not look like an iptables command. at /usr/sbin/psad line 6701.
```
Using version 2.2.5 with the same `psad.conf` works ok 

I have the iptables binary set correctly in `psad.conf` but it doesn't seem to be picked up:
```
### system binaries
iptablesCmd      /sbin/iptables;
```
The quickest way to check this is probably with an [Alpine LXC container](http://wiki.alpinelinux.org/wiki/LXC)

**Comment by mrash** [comment]
I believe this issue is fixed in git master now. There are two paths to fix the issue on your system - either upgrade the IPTables::Parse and IPTables::ChainMgr modules, or clone the psad git repository and try the latest psad code. I'll probably go ahead and make a new release soon to get this fix out to the user community. Thanks for catching this issue.

**Comment by itoffshore** [comment]
I've [submitted patches to Alpine](http://patchwork.alpinelinux.org/project/aports/list) to update `perl-iptables-chainmgr` & `perl-iptables-parse` & this fixed the error - many thx.

**Comment by mrash** [comment]
Ok, great. psad-2.4.1 will also contain the fix so that backwards compatibility is maintained even when there are older versions of the IPTables::ChainMgr module is installed.
